export { GeneralPage } from './general-page'
export { RegistrationPage } from './registration-page'
export { LoginPage } from './login-page'
export { AdminPanelPage } from './admin-panel-page'
export { AboutUsPage } from './about-us-page'
